// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzpmzdcmwgxduohglruh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cG16ZGNtd2d4ZHVvaGdscnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjczNzgsImV4cCI6MjA3MDAwMzM3OH0.dQG0k7FGJY09nicitaFy7Ipa5iGDHeoE0OnaAS0WK0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});