name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            export DEBIAN_FRONTEND=noninteractive

            if command -v apt >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y nginx git curl python3 ca-certificates
              if ! command -v node >/dev/null 2>&1; then
                curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                sudo apt install -y nodejs
              fi
            fi

            # Подготовка директории проекта
            sudo mkdir -p /var/www
            if [ ! -d /var/www/site/.git ]; then
              sudo rm -rf /var/www/site
              sudo git clone https://github.com/GenioFalco/tech-showcase-shop.git /var/www/site
            fi

            cd /var/www/site
            sudo git fetch --all --prune
            sudo git reset --hard origin/main

            # Сборка
            sudo npm ci || sudo npm install
            sudo npm run build

            # Вычисляем punycode домена
            puny=$(python3 - << 'PY'
import idna
print(idna.encode('тысяча-мелочей.рф').decode())
PY
)

            # Настройка Nginx
            sudo tee /etc/nginx/sites-available/tech-showcase-shop >/dev/null <<CONF
server {
  listen 80;
  listen [::]:80;
  server_name $puny;

  root /var/www/site/dist;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  access_log /var/log/nginx/tech-showcase-shop.access.log;
  error_log  /var/log/nginx/tech-showcase-shop.error.log;
}
CONF

            sudo rm -f /etc/nginx/sites-enabled/default
            sudo ln -sf /etc/nginx/sites-available/tech-showcase-shop /etc/nginx/sites-enabled/tech-showcase-shop
            sudo nginx -t
            sudo systemctl enable --now nginx
            sudo systemctl reload nginx
